version: '2.1'
services:
  echod:
    image: hashicorp/http-echo
    command: ["-text", "works!", "-listen", ":1337"]
    networks:
      echod_network:
        ipv6_address: fd00:1337:TEAMID:ecc0::1
    restart: unless-stopped

networks:
  echod_network:
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: fd00:1337:TEAMID:ecc0::/64
          gateway: fd00:1337:TEAMID:ecc0::ffff