---
# For complaints please contact Niklas (@nij.red)
  - name: Enable (stopped state) radvd
    systemd:
      name: "radvd"
      state: stopped
      enabled: yes

  - name: Enable (stopped state) dhcpd
    systemd:
      name: "isc-dhcp-server"
      state: stopped
      enabled: yes

  - name: Enable and (re)start openvpn connection
    systemd:
      name: "openvpn@routers"
      state: restarted
      enabled: yes

