---
# Created by Niklas Jacob for ENOWARS3
  - name: Create /home/testd
    file:
      path: /home/testd
      state: directory
      mode: 0755

  - name: Upload testd's docker-compose.yml
    copy:
      src: docker-compose.yml
      dest: /home/testd/docker-compose.yml.template