---
  - name: Install tcpdump
    apt: 
      name: tcpdump
      state: present 
      update_cache: yes
  
  - name: Ensure ~/.ssh exists
    file:
      path: ~/.ssh
      state: directory

  - name: Copy over the key
    copy:
      src: priv_key_for_moloch
      dest: ~/.ssh/priv_key_for_moloch
    changed_when: false

  - name: ensure key file permissions
    file:
      path: ~/.ssh/priv_key_for_moloch
      mode: '0600'

  - name: Copy over the enodump unit
    copy:
      src: enodump.service
      dest: /etc/systemd/system/enodump.service
    changed_when: false

  - name: Reload system daemon
    systemd:
      name: "enodump" # ansible <2.4 always requires 'name'
      daemon_reload: yes

  - name: Ensure /pcaps exists
    file:
      path: /pcaps
      state: directory

  - name: Ensure /pcaps/data exists
    file:
      path: /pcaps/data
      state: directory
  
  - name: Copy over the send_pcaps script
    copy:
      src: send_pcap.sh
      dest: /pcaps/send_pcap.sh
    changed_when: false

  - name: Enable and start enodump
    service:
      name: enodump
      enabled: yes
