---
  - name: Increase max_map_count
    sysctl:
      name: vm.max_map_count
      value: 262144
      sysctl_set: yes

  - name: Disable and stop EnoMoloch
    service:
      name: dc@EnoMoloch
      state: stopped
      enabled: no

  - name: Install tcpdump
    apt: 
      name: tcpdump
      state: present 
      update_cache: yes
  
  - name: Copy over the router key
    copy:
      src: router_key
      dest: /router_key
    changed_when: false

  - name: Add router key
    authorized_key:
      user: root
      state: present
      key: "/router_key" 

  - name: Ensure /services exists
    file:
      path: /services
      state: directory
  
  - name: Ensure /pcaps exists
    file:
      path: /pcaps
      state: directory

  - name: Ensure /services/EnoMoloch exists
    file:
      path: /services/EnoMoloch
      state: directory

  - name: Copy over the EnoMoloch docker-compose file
    copy:
      src: docker-compose.yml
      dest: /services/EnoMoloch/docker-compose.yml
    changed_when: false


  - name: Enable and start EnoMoloch
    service:
      name: dc@EnoMoloch
      enabled: yes
