---
  - name: Increase max_map_count
    sysctl:
      name: vm.max_map_count
      value: 262144
      sysctl_set: yes

  - name: Install docker dependencies
    apt:
      name: ["git"]
      state: present

  - name: Clone EnoELK
    git:
      repo: "https://github.com/enowars/EnoELK.git"
      dest: /services/EnoELK

  - name: Copy over the EnoELK unit
    copy:
      src: EnoELK.service
      dest: /etc/systemd/system/EnoELK.service
    changed_when: false

  - name: Reload system daemon
    systemd:
      name: "EnoELK" # ansible <2.4 always requires 'name'
      daemon_reload: yes

  - name: Enable EnoELK
    service:
      name: EnoELK
      enabled: yes
