---
  - hosts: aptrepo
    become: yes
    become_user: "root"
    become_method: "sudo"
    gather_facts: yes

    roles:
      - pre_configs
      - programs
      - timezone
      - locales 
      - hostname
      - motd
      - docker
      - router
      - router_ip
      - apt-server


    vars:
      program_list:
        - vim
        - htop
        - tmux
        - vnstat
        - tcpdump
        - dnsutils
        - rsync
        - netcat-openbsd