---
  - hosts: all
    become: yes
    become_method: sudo
    vars_files:
      - config_bambi.yml
      - enomoloch-get-pcaps
    roles:
        - bambi-ssh-keys
        - firewall
        - wireguard
        - enomoloch
        - role: filebeat
          vars:
            elk: {{ elk_address }}
        - role: journalbeat
          vars:
            elk: {{ elk_address }}
        - role: metricbeat
          vars:
            elk: {{ elk_address }}
