---
  - hosts: all
    become: yes
    become_method: sudo
    vars_files:
      - config_bambi.yml

    roles:
      - bambi-ssh-keys
      - firewall
      - wireguard
      - enoelk
      - docker-block-external
      - role: programs
        vars:
          program_list: "tmux"