---
  - hosts: all
    become: yes
    become_method: sudo
    vars_files:
      - config_bambi.yml

    roles:
      - bambi-ssh-keys
      - firewall
      - wireguard
      - enoengine
      - enoelk
      - bambi-scoreboard
      - role: filebeat
        vars:
          elk: {{ elk_adress }}
      - role: journalbeat
        vars:
          elk: {{ elk_adress }}
      - role: metricbeat
        vars:
          elk: {{ elk_adress }}
      - docker-block-external
      - role: programs
        vars:
          program_list: "tmux"
