---
  - hosts: all
    become: yes
    become_method: sudo
    vars_files:
      - config_bambi.yml

    roles:
      - bambi-ssh-keys
      - firewall
      - wireguard
      - role: filebeat
        vars:
          elk: {{ elk_address }}
      - role: journalbeat
        vars:
          elk: {{ elk_address }}
      - role: metricbeat
        vars:
          elk: {{ elk_address }}
      - vuln_checkers
      - docker-block-external
      - role: programs
        vars:
          program_list: "tmux"
