version: "3"
services: 
  traefik:
    image: traefik:alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.toml:/traefik.toml
      - ./logs:/logs
    networks:
      - enoverlay
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    restart: always
networks:
    enoverlay:
            external: true