---
  - name: Make the Journal persistent across boots and adjust rate limits
    replace:
      path: /etc/systemd/journald.conf
      regexp: "{{ item.regex }}"
      replace: "{{ item.replace }}"
    with_items:
      - { "regex": '^#?Storage=.*$', "replace": "Storage=persistent" }
      - { "regex": '^#?RateLimitIntervalSec=.*$', "replace": "RateLimitIntervalSec=0" }
      - { "regex": '^#?RateLimitBurst=.*$', "replace": "RateLimitBurst=0" }
