---
  - name: Copy apt key to vulnbox
    copy:
      src: enowars.apt.pub.gpg
      dest: /tmp/enowars.apt.pub.gpg

  - name: Import apt key
    apt_key:
      file: /tmp/enowars.apt.pub.gpg
      state: present

  - name: Delete /tmp/enowars.apt.pub.gpg
    file:
      name: /tmp/enowars.apt.pub.gpg 
      state: absent

  - name: Copy enowars.list to vulnbox
    template:
      src: enowars.list.j2
      dest: /etc/apt/sources.list.d/enowars.list

  - name: Set always ask option in /etc/apt/apt.conf.d/00-ask
    blockinfile:
      path: /etc/apt/apt.conf.d/00-ask
      block: |
        Dpkg::Options {
          "--force-confask"
        }
      create: yes

  # - name: Update apt
  #   apt:
  #     update_cache: yes