---
# For complaints please contact Niklas (@nij.red)
  - name: Install openvpn, radvd and dhcpd
    apt:
      name: ['openvpn', 'radvd', 'isc-dhcp-server']
      force_apt_get: yes
      cache_valid_time: 3000
      state: present
    notify:
    - Enable (stopped state) dhcpd
    - Enable (stopped state) radvd

  - name: Upload router key
    copy:
      src: client.key
      dest: /etc/openvpn/client/router.key
      owner: root
      group: root
      mode: 0600
    notify: Enable and (re)start openvpn connection

  - name: Upload router certificate
    copy:
      src: client.crt
      dest: /etc/openvpn/client/router.crt
      owner: root
      group: root
      mode: 0600
    notify: Enable and (re)start openvpn connection

  - name: Upload router CA certificate
    copy:
      src: ca.crt
      dest: /etc/openvpn/client/router-ca.crt
      owner: root
      group: root
      mode: 0600
    notify: Enable and (re)start openvpn connection

  - name: Upload router tls key
    copy:
      src: ta.key
      dest: /etc/openvpn/client/router-ta.key
      owner: root
      group: root
      mode: 0600
    notify: Enable and (re)start openvpn connection

  - name: Upload setup-iface.sh
    copy:
      src: setup-iface.sh
      dest: /etc/openvpn/client/setup-iface.sh
      owner: root
      group: root
      mode: 0700
    notify: Enable and (re)start openvpn connection

  - name: Upload openvpn config
    template:
      src: routers.conf.j2
      dest: /etc/openvpn/routers.conf
      owner: root
      group: root
      mode: 0600
    notify: Enable and (re)start openvpn connection

  - name: Upload subnet radvd config
    copy:
      src: radvd.conf.subnet
      dest: /etc/radvd.conf.subnet
      owner: root
      group: root
      mode: 0600

  - name: Upload address radvd config
    copy:
      src: radvd.conf.address
      dest: /etc/radvd.conf.address
      owner: root
      group: root
      mode: 0600

  - name: Upload docker radvd config
    copy:
      src: radvd.conf.docker
      dest: /etc/radvd.conf.docker
      owner: root
      group: root
      mode: 0600

  - name: Enable ipv6 forawarding
    sysctl:
      name: net.ipv6.conf.all.forwarding
      value: 1
      state: present

  - name: Upload dhcpd config
    copy:
      src: dhcpd6.conf.orig
      dest: /etc/dhcp/dhcpd6.conf.orig
      owner: root
      group: root
      mode: 0600

  - name: Upload network-setup script
    copy:
      src: network-setup.sh
      dest: /usr/bin/network-setup
      owner: root
      group: root
      mode: 0750

