---
  - name: Create /packages
    file:
      path: /packages
      state: directory

  - name: Create /home/aptly
    file:
      path: /home/aptly
      state: directory

  - name: Upload docker-compose.yml to /home/aptly/
    copy:
      src: docker-compose.yml
      dest: /home/aptly/docker-compose.yml

  - name: Upload Dockerfile to /home/aptly/
    copy:
      src: Dockerfile
      dest: /home/aptly/Dockerfile

  - name: Upload nginx.conf to /home/aptly/
    copy:
      src: nginx.conf
      dest: /home/aptly/nginx.conf

  - name: Upload aptly.conf to /home/aptly/
    copy:
      src: aptly.conf
      dest: /home/aptly/aptly.conf

  - name: Upload enowars.priv.gpg to /home/aptly/
    copy:
      src: enowars.priv.gpg
      dest: /home/aptly/enowars.priv.gpg

  - name: Upload enowars.pub.gpg to /home/aptly/
    copy:
      src: enowars.pub.gpg
      dest: /home/aptly/enowars.pub.gpg

  - name: Upload ED75B5A4483DA07C.pub to /home/aptly/
    copy:
      src: ED75B5A4483DA07C.pub
      dest: /home/aptly/ED75B5A4483DA07C.pub

  - name: Upload repo.sh to /home/aptly/
    copy:
      src: repo.sh
      dest: /home/aptly/repo.sh
      owner: root
      group: root 
      mode: 750

  - name: Run docker-compose up --build
    shell: /usr/local/bin/docker-compose up --build -d
    args:
      chdir: /home/aptly